Class {
	#name : 'RowanSample2E',
	#superclass : 'RowanSample2B',
	#instVars : [
		'e',
		'ivar2'
	],
	#category : 'RowanSample2-Core'
}

{ #category : 'accessing' }
RowanSample2E >> e [

	^ e
]

{ #category : 'accessing' }
RowanSample2E >> e: anObject [

	e := anObject
]

{ #category : 'accessing' }
RowanSample2E >> ivar2 [

	^ ivar2
]

{ #category : 'accessing' }
RowanSample2E >> ivar2: anObject [

	ivar2 := anObject
]
