Class {
	#name : 'RowanSample2',
	#superclass : 'Object',
	#instVars : [
		'ivar0',
		'ivar1',
		'ivar2'
	],
	#category : 'RowanSample2-Core'
}

{ #category : 'accessing' }
RowanSample2 >> foo [ ^'foo'
]

{ #category : 'accessing' }
RowanSample2 >> ivar0 [

	^ ivar0
]

{ #category : 'accessing' }
RowanSample2 >> ivar0: anObject [

	ivar0 := anObject
]

{ #category : 'accessing' }
RowanSample2 >> ivar1 [

	^ ivar1
]

{ #category : 'accessing' }
RowanSample2 >> ivar1: anObject [

	ivar2 := anObject
]

{ #category : 'accessing' }
RowanSample2 >> ivar2 [

	^ ivar2
]

{ #category : 'accessing' }
RowanSample2 >> ivar2: anObject [

	ivar1 := anObject
]
