Class {
	#name : 'RowanSample2D',
	#superclass : 'RowanSample2A',
	#instVars : [
		'd',
		'ivar2'
	],
	#category : 'RowanSample1-Core'
}

{ #category : 'accessing' }
RowanSample2D >> d [

	^ d
]

{ #category : 'accessing' }
RowanSample2D >> d: anObject [

	d := anObject
]

{ #category : 'accessing' }
RowanSample2D >> ivar2 [

	^ ivar2
]

{ #category : 'accessing' }
RowanSample2D >> ivar2: anObject [

	ivar2 := anObject
]
