Class {
	#name : 'RowanSample2C',
	#superclass : 'RowanSample2A',
	#instVars : [
		'c',
		'ivar2'
	],
	#category : 'RowanSample2-Core'
}

{ #category : 'accessing' }
RowanSample2C >> c [

	^ c
]

{ #category : 'accessing' }
RowanSample2C >> c: anObject [

	c := anObject
]

{ #category : 'accessing' }
RowanSample2C >> ivar2 [

	^ ivar2
]

{ #category : 'accessing' }
RowanSample2C >> ivar2: anObject [

	ivar2 := anObject
]
