Class {
	#name : 'RowanSample2F',
	#superclass : 'RowanSample2B',
	#instVars : [
		'f',
		'ivar2'
	],
	#category : 'RowanSample1-Core'
}

{ #category : 'accessing' }
RowanSample2F >> f [

	^ f
]

{ #category : 'accessing' }
RowanSample2F >> f: anObject [

	f := anObject
]

{ #category : 'accessing' }
RowanSample2F >> ivar2 [

	^ ivar2
]

{ #category : 'accessing' }
RowanSample2F >> ivar2: anObject [

	ivar2 := anObject
]
